import type { Metadata } from "next"
import { Noto_Sans_JP as FontSans } from "next/font/google"
import "./globals.css"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Silent Face App",
  description: "Generated by create Silent Face App",
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <body>
        <header className="bg-white shadow-md p-4 mb-6">
          <h1>Silent Face</h1>
        </header>
        <main>
                {children}
        </main>
        <footer className="text-center text-sm text-gray-500 mt-10 py-4 border-t">
          &copy; 2025 Silent Face Appa
        </footer>
      </body>
    </html>
  )
}
